//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Users = new HashSet<User>();
            this.Phases = new HashSet<Phase>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Budget { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Phase> Phases { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
