//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> PhaseId { get; set; }
        public int ProjectId { get; set; }
        public int TaskTypeId { get; set; }
        public int TaskStatusId { get; set; }
        public Nullable<int> PhaseId1 { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual TaskType TaskType { get; set; }
        public virtual TaskStatus TaskStatus { get; set; }
        public virtual Phase Phase { get; set; }
    }
}
